--1. Personel tablosu 
CREATE TABLE STAFF (
    StaffID INT PRIMARY KEY IDENTITY (1,1),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL, -- Bu eksikti, ekledik.
    Title NVARCHAR (50) NOT NULL,
    Phone NVARCHAR (15) NOT NULL,
    IsActive BIT DEFAULT 1
);
--2. Oda Tipleri 
CREATE TABLE ROOMTYPES(
RoomTypeID INT PRIMARY KEY IDENTITY (1,1),
TypeName NVARCHAR(50) NOT NULL,
BasePrice DECIMAL (18,2) NOT NULL,
MaxCapacity INT NOT NULL 
);

--3. Misafirler (GUESTS)
CREATE TABLE GUESTS (
    GuestID INT PRIMARY KEY IDENTITY (1,1),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    IdentityNumber NVARCHAR(20) NOT NULL UNIQUE,
    Nationality CHAR(2) DEFAULT 'TR',
    PhoneNumber NVARCHAR(15),
    Email NVARCHAR(100) NOT NULL UNIQUE,
    CreatedAt DATETIME DEFAULT GETDATE()
);

--4. ODALAR Tablosu 
CREATE TABLE ROOMS(
RoomID INT PRIMARY KEY IDENTITY(1,1),
RoomNumber NVARCHAR (10) NOT NULL UNIQUE,
RoomTypeID INT NOT NULL,
Status NVARCHAR (20) DEFAULT 'Available',
CONSTRAINT FK_Rooms_RoomTypes FOREIGN KEY (RoomTypeID) REFERENCES ROOMTYPES(RoomTypeID)
);

--5. Rezervasyon Tablosu 
CREATE TABLE RESERVATIONS (
ResID INT PRIMARY KEY IDENTITY (1,1),
GuestID INT NOT NULL,
RoomID INT NOT NULL ,
CreatedByStaffID INT NOT NULL,
CheckInDate DATE NOT NULL ,
CheckOutDate DATE NOT NULL ,
TotalAmount DECIMAL (12,2),
IsActive BIT DEFAULT 1,
CONSTRAINT FK_Res_Guest FOREIGN KEY (GuestID) REFERENCES GUESTS(GuestID),
CONSTRAINT FK_Res_Room FOREIGN KEY (RoomID) REFERENCES ROOMS(RoomID),
CONSTRAINT FK_Res_Staff FOREIGN KEY (CreatedByStaffID) REFERENCES STAFF(StaffID),
CONSTRAINT CHK_Dates CHECK (CheckOutDate > CheckInDate)

);
--6. ÖDEMELER Tablosu 
CREATE TABLE PAYMENTS (
PaymentID INT PRIMARY KEY IDENTITY(1,1),
ResID INT NOT NULL ,
PaymentDate DATETIME DEFAULT GETDATE(),
Amount DECIMAL(12,2) NOT NULL,
PaymentMethod NVARCHAR(50),
CONSTRAINT FK_Payments_Res FOREIGN KEY (ResID) REFERENCES RESERVATIONS(ResID)
);

--7. Ekstra Hizmetler Tablosu
CREATE TABLE SERVICES (
    ServiceID INT PRIMARY KEY IDENTITY(1,1),
    ResID INT NOT NULL,
    ServiceName NVARCHAR(100) NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    ServiceDate DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_Services_Res FOREIGN KEY (ResID) REFERENCES RESERVATIONS(ResID)
);